name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - name: Test (NUnit)
        run: |
          dotnet test --configuration Release --no-build \
            --logger "trx;LogFileName=TestResults.trx" \
            --logger "console;verbosity=detailed" \
            --results-directory TestResults
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults
