name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - name: Test (NUnit)
        run: |
          dotnet test --configuration Release --no-build \
            --logger "trx;LogFileName=TestResults.trx" \
            --logger "console;verbosity=detailed" \
            --results-directory TestResults
      - name: Set up Java
        if: always()
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Allure report (CLI)
        if: always()
        run: |
          set -e
          curl -L -o allure.zip https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.29.0/allure-commandline-2.29.0.zip
          unzip -q allure.zip -d allure-cli
          ./allure-cli/allure-2.29.0/bin/allure generate --clean allure-results -o allure-report
          echo "Generated report contents:" && ls -la allure-report || true

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/**

      - name: Upload Allure HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report