name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      
      - name: Test (NUnit)
        run: |
          dotnet test --configuration Release --no-build \
            --logger "trx;LogFileName=TestResults.trx" \
            --logger "console;verbosity=detailed" \
            --results-directory TestResults
`
      - name: Gather Allure results
        if: always()
        run: |
          set -e
          mkdir -p allure-results
          find . -type d -name "allure-results" -exec sh -c 'cp -rv "$1"/* allure-results/ || true' _ {} \;
          echo "JSON count: $(ls allure-results/*.json 2>/dev/null | wc -l || true)"


      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: 'allure-results'
          allure_report: 'allure-report'
      
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/**
          overwrite: true          

      - name: Upload Allure HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: allure-report
         path: allure-report
         overwrite: true