name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - name: Test (NUnit)
        run: |
          dotnet test --configuration Release --no-build \
            --logger "trx;LogFileName=TestResults.trx" \
            --logger "console;verbosity=detailed" \
            --results-directory TestResults
      - name: Set up Java
        if: always()
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Allure report (CLI)
        if: always()
        run: |
          set -e
          mkdir -p allure-results
          echo "Searching for allure-results folders..."
          find . -type d -name "allure-results" -print
          echo "Copying contents..."
          find . -type d -name "allure-results" -exec sh -c 'cp -rv "$1"/* allure-results/ || true' _ {} \;
          echo "Final listing:"
          ls -la allure-results || true
          echo "JSON count: $(ls allure-results/*.json 2>/dev/null | wc -l || true)"
          echo "PNG  count: $(ls allure-results/*.png  2>/dev/null | wc -l || true)"

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/**

      - name: Upload Allure HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure_results
          path: allure-results